(() => {
 const dom=globalThis.AccessibleToolsDom;if(!dom)return;const VERSION='0.5.0',HEARTBEAT_MS=1000;let session=null,heartbeatId=null,activationInProgress=false;
 function safeLocation(){try{const pathname=String(location.pathname||'/');const parts=pathname.split('/').filter(Boolean);const sensitive=new Set(['c','g','share','project','projects']);const safePath=parts.length&&sensitive.has(parts[0].toLowerCase())?`/${parts[0]}/[redacted]`:pathname;return`${location.origin}${safePath}`;}catch{return'/';}}
 function newDiagnostics(reason,toolId=null){stopHeartbeat();const startedAt=Date.now();session={version:VERSION,sessionId:`${startedAt}-${Math.random().toString(36).slice(2,8)}`,reason,toolId,startedAt,startedAtIso:new Date(startedAt).toISOString(),events:[]};record('session-start',{url:safeLocation(),viewport:{width:innerWidth,height:innerHeight,fullscreen:Boolean(document.fullscreenElement)},visibilityState:document.visibilityState});}
 function record(event,details={}){if(!session)newDiagnostics('implicit');session.events.push({at:new Date().toISOString(),elapsedMs:Date.now()-session.startedAt,event,details});if(session.events.length>600)session.events.splice(0,session.events.length-600);}
 function captureSafeState(toolId=null){const plus=dom.findPlusButton(),marker=toolId?dom.findComposerToolMarker(toolId):null,pills=dom.composerPillSnapshot();return{plusFound:Boolean(plus),plusExpanded:plus?.getAttribute('aria-expanded')||'',composerFound:Boolean(dom.findComposer()),composerRootFound:Boolean(dom.findComposerRoot()),requestedToolMarkerFound:Boolean(marker),evidenceKind:marker?.evidenceKind||'',requestedToolMarker:marker?dom.safeElementSummary(marker.element):null,inlinePillCount:pills.length,composerPills:pills,activationInProgress,fullscreen:Boolean(document.fullscreenElement),viewport:{width:innerWidth,height:innerHeight}};}
 function startHeartbeat(toolId){stopHeartbeat();record('heartbeat',captureSafeState(toolId));heartbeatId=setInterval(()=>record('heartbeat',captureSafeState(toolId)),HEARTBEAT_MS);}
 function stopHeartbeat(){if(heartbeatId!=null){clearInterval(heartbeatId);heartbeatId=null;}}
 function setActivationInProgress(v){activationInProgress=Boolean(v);}
 function announce(message,assertive=true){let el=document.getElementById(dom.STATUS_ID);if(!el){el=document.createElement('div');el.id=dom.STATUS_ID;el.setAttribute(dom.OWNED_ATTR,'true');el.setAttribute('role','status');el.setAttribute('aria-atomic','true');Object.assign(el.style,{position:'fixed',width:'1px',height:'1px',margin:'-1px',overflow:'hidden',clip:'rect(0,0,0,0)',whiteSpace:'nowrap',border:'0'});document.documentElement.appendChild(el);}el.setAttribute('aria-live',assertive?'assertive':'polite');el.textContent='';setTimeout(()=>{el.textContent=message;},30);}
 function diagnosticReportText(){if(!session)newDiagnostics('manual-download');const lines=['ДІАГНОСТИЧНИЙ ЗВІТ — ДОСТУПНІ ІНСТРУМЕНТИ',`Версія: ${VERSION}`,`Сеанс: ${session.sessionId}`,`Причина: ${session.reason}`,`Інструмент: ${session.toolId||'(немає)'}`,`Початок: ${session.startedAtIso}`,`Створено: ${new Date().toISOString()}`,`URL: ${safeLocation()}`,'Конфіденційність: текст запиту/чату не записується; ідентифікатор розмови в URL приховано.','','ХРОНОЛОГІЯ'];for(const e of session.events)lines.push(`[+${(e.elapsedMs/1000).toFixed(3)}s] ${e.at} ${e.event} ${JSON.stringify(e.details)}`);return lines.join('\n');}
 function diagnosticsFilename(){return`діагностика-доступних-інструментів-${new Date().toISOString().replace(/[:.]/g,'-').replace('T','_').replace('Z','')}.txt`;}
 function downloadDiagnostics(){record('diagnostic-download-requested',captureSafeState(session?.toolId||null));const report=diagnosticReportText(),blob=new Blob([report],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.setAttribute(dom.OWNED_ATTR,'true');a.href=url;a.download=diagnosticsFilename();a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Діагностичний звіт завантажено.',false);}
 newDiagnostics('page-ready');globalThis.AccessibleToolsDiagnostics=Object.freeze({VERSION,HEARTBEAT_MS,newDiagnostics,record,captureSafeState,startHeartbeat,stopHeartbeat,setActivationInProgress,announce,diagnosticReportText,downloadDiagnostics});
})();
