(() => {
  const api=globalThis.ChatGPTToolPicker;if(!api)return;
  const OWNED_ATTR='data-accessible-tools-owned',STATUS_ID='accessible-tools-status';
  const VERIFY_TIMEOUT_MS=6000,VERIFY_STABLE_MS=300;
  const PLUS_SELECTORS=['[data-testid="composer-plus-btn"]','#composer-plus-btn','button[aria-label="Додати файли та інше"]','button[aria-haspopup="menu"][aria-label*="файл" i]','button[aria-haspopup="menu"][aria-label*="files" i]'];
  const INTERACTIVE_SELECTOR=['[role="menuitem"]','[role="menuitemradio"]','[role="menuitemcheckbox"]','[role="option"]','div.__menu-item','[data-fill][tabindex]','button','a[href]','[tabindex]'].join(',');
  const MENU_SURFACE_SELECTOR=['[role="menu"]','[role="listbox"]','[role="menuitem"]','[role="menuitemradio"]','[role="menuitemcheckbox"]','[role="option"]','.__menu-item','[data-fill][tabindex]','[data-radix-menu-content]','[data-radix-popper-content-wrapper]','[popover]'].join(',');
  function isVisible(el){if(!(el instanceof Element)||el.hidden||el.getAttribute('aria-hidden')==='true')return false;const s=window.getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&el.getClientRects().length>0;}
  function findPlusButton(){for(const s of PLUS_SELECTORS){const el=document.querySelector(s);if(el instanceof HTMLElement&&isVisible(el))return el;}return null;}
  function findComposer(){for(const s of ['#prompt-textarea','[data-testid="composer-input"]','[data-testid*="composer"][contenteditable="true"]','textarea[placeholder]','[contenteditable="true"][aria-label*="message" i]','[contenteditable="true"][aria-label*="повідом" i]','[contenteditable="true"][aria-label*="ChatGPT" i]']){const el=document.querySelector(s);if(el instanceof HTMLElement&&isVisible(el))return el;}return null;}
  function findComposerRoot(){const c=findComposer();if(c instanceof HTMLElement){const r=c.closest('[data-type="unified-composer"], form');if(r instanceof HTMLElement&&isVisible(r))return r;if(c.parentElement instanceof HTMLElement)return c.parentElement;}const r=document.querySelector('[data-type="unified-composer"]');return r instanceof HTMLElement&&isVisible(r)?r:null;}
  function focusComposer(){findComposer()?.focus({preventScroll:true});}
  function extensionOwned(el){return Boolean(el?.closest?.(`[${OWNED_ATTR}="true"], #${STATUS_ID}`));}
  function inEditable(el){return Boolean(el?.closest?.('#prompt-textarea, textarea, input, [contenteditable="true"], [role="textbox"]'));}
  function menuLike(el){return Boolean(el?.closest?.(MENU_SURFACE_SELECTOR));}
  function classifyComposerToolMarker(toolId,el){if(!(el instanceof Element)||!isVisible(el)||extensionOwned(el)||menuLike(el))return null;if(api.isToolSelectionPill?.(toolId,el))return{element:el,evidenceKind:'inline-selection-pill'};if(!inEditable(el)&&api.isSelected(el)&&api.matchesToolSelectionIdentity?.(toolId,el))return{element:el,evidenceKind:'selected-control'};if(!inEditable(el)&&el.matches('button.__composer-pill')&&api.isToolLabel(toolId,api.accessibleText(el)))return{element:el,evidenceKind:'composer-pill'};return null;}
  function findComposerToolMarker(toolId){const r=findComposerRoot();if(!(r instanceof Element))return null;for(const el of r.querySelectorAll('[data-inline-selection-pill],[data-symbol="ecosystemMention"],[aria-pressed="true"],[aria-checked="true"],[data-state="checked"],[data-state="active"],[data-state="selected"],button.__composer-pill')){const hit=classifyComposerToolMarker(toolId,el);if(hit)return hit;}return null;}
  function safeElementSummary(el){if(!(el instanceof Element))return null;return{tag:el.tagName?.toLowerCase()||'',role:el.getAttribute('role')||'',ariaLabel:String(el.getAttribute('aria-label')||'').slice(0,120),dataTestId:el.getAttribute('data-testid')||'',dataState:el.getAttribute('data-state')||'',dataId:el.getAttribute('data-id')||'',dataSystemHintType:el.getAttribute('data-system-hint-type')||'',dataKeyword:String(el.getAttribute('data-keyword')||'').slice(0,100),dataSymbol:el.getAttribute('data-symbol')||'',inlineSelectionPill:el.hasAttribute('data-inline-selection-pill'),ariaChecked:el.getAttribute('aria-checked')||'',ariaPressed:el.getAttribute('aria-pressed')||''};}
  function composerPillSnapshot(){const r=findComposerRoot();if(!(r instanceof Element))return[];return[...r.querySelectorAll('[data-inline-selection-pill],[data-symbol="ecosystemMention"]')].filter(el=>isVisible(el)&&!extensionOwned(el)&&!menuLike(el)).slice(0,12).map(safeElementSummary);}
  function toInteractive(el){return el?.matches?.(INTERACTIVE_SELECTOR)?el:el?.closest?.(INTERACTIVE_SELECTOR);}
  function isInOpenPopup(el){return Boolean(el instanceof Element&&isVisible(el)&&menuLike(el));}
  function findToolCandidate(toolId,baseline=null,{requireMenuSurface=false}={}){const set=new Set(document.querySelectorAll(INTERACTIVE_SELECTOR));for(const el of document.querySelectorAll('span,div')){if(extensionOwned(el))continue;const text=String(el.textContent||'').replace(/\s+/g,' ').trim();if(!text||text.length>180)continue;if(api.isToolLabel(toolId,text)||api.isToolDescription(toolId,text)){const t=toInteractive(el);if(t)set.add(t);}}return[...set].filter(isVisible).filter(el=>!extensionOwned(el)).filter(el=>!requireMenuSurface||isInOpenPopup(el)).filter(el=>!baseline||!baseline.has(el)||isInOpenPopup(el)).map(element=>({element,score:api.scoreToolCandidate(toolId,element)})).filter(x=>x.score>=100).sort((a,b)=>b.score-a.score)[0]?.element||null;}
  function waitFor(getter,timeoutMs){return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;obs.disconnect();clearInterval(poll);clearTimeout(timer);resolve(v);};const check=()=>{const v=getter();if(v)finish(v);};const obs=new MutationObserver(check);obs.observe(document.body||document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['role','data-state','aria-hidden','aria-expanded','aria-checked','aria-pressed','data-id','data-system-hint-type','data-symbol','data-inline-selection-pill']});const poll=setInterval(check,100),timer=setTimeout(()=>finish(null),timeoutMs);});}
  function waitForToolCandidate(toolId,baseline,timeoutMs=4500){const c=findToolCandidate(toolId,baseline,{requireMenuSurface:true});return c?Promise.resolve(c):waitFor(()=>findToolCandidate(toolId,baseline,{requireMenuSurface:true}),timeoutMs);}
  function waitForComposerToolMarker(toolId,timeoutMs=VERIFY_TIMEOUT_MS){let since=0,last=null;return waitFor(()=>{const hit=findComposerToolMarker(toolId);if(!hit){since=0;last=null;return null;}if(hit.element!==last){last=hit.element;since=Date.now();return null;}return Date.now()-since>=VERIFY_STABLE_MS?hit:null;},timeoutMs);}
  function robustClick(el){if(!(el instanceof HTMLElement))return;el.scrollIntoView?.({block:'nearest',inline:'nearest'});el.focus?.({preventScroll:true});const i={bubbles:true,cancelable:true,composed:true,button:0};try{if(typeof PointerEvent==='function')el.dispatchEvent(new PointerEvent('pointerdown',{...i,pointerType:'mouse'}));el.dispatchEvent(new MouseEvent('mousedown',i));if(typeof PointerEvent==='function')el.dispatchEvent(new PointerEvent('pointerup',{...i,pointerType:'mouse'}));el.dispatchEvent(new MouseEvent('mouseup',i));}catch{}el.click();}
  globalThis.AccessibleToolsDom=Object.freeze({OWNED_ATTR,STATUS_ID,VERIFY_STABLE_MS,INTERACTIVE_SELECTOR,isVisible,findPlusButton,findComposer,findComposerRoot,focusComposer,findComposerToolMarker,classifyComposerToolMarker,composerPillSnapshot,safeElementSummary,findToolCandidate,waitForToolCandidate,waitForComposerToolMarker,robustClick});
})();
